zsh: fix cze nvim

diff --git a/dot_zshrc.tmpl b/dot_zshrc.tmpl
--- a/dot_zshrc.tmpl
+++ b/dot_zshrc.tmpl
@@ -202,15 +202,15 @@ function gtdci {
 
 function cze {
   if [[ -z "$1" ]]; then
-    echo "File required" >&2
+    echo "File/dir required" >&2
     return 1
   fi
 
   case "$1" in
     # edit file directly so that pane navigation continues to work
-    nvim) vim ~/.local/share/chezmoi/private_dot_config/nvim; return 0;;
-    wezterm) chezmoi edit ~/.config/wezterm/wezterm.lua; return 0;;
-    zsh) chezmoi edit ~/.zshrc; return 0;;
+    nvim) nvim ~/.local/share/chezmoi/private_dot_config/nvim/;;
+    wezterm) chezmoi edit ~/.config/wezterm/wezterm.lua;;
+    zsh) chezmoi edit ~/.zshrc;;
   esac
 
   chezmoi edit "$1"
